Feat/add ts no shadow
alfa-laboratory/arui-presets-lint pull request #122
Opened 2021-02-26 09:01 UTC by PoytaL

Изменение no-shadow проверки

## Мотивация и контекст
При обновлении на проектах версии TypeScript до 4+ возникает необходимость повышения версии typescript-eslint.
В typescript-eslint 4.0+ возникает баг на объявлениях enum.
<img width="631" alt="Снимок экрана 2021-02-26 в 11 34 51" src="https://user-images.githubusercontent.com/76110903/109276182-c094ce00-7826-11eb-9757-e301361337d9.png">
Изменения выключают стандартную проверку no-shadow, заменяя ее на проверку @typescript-eslint/no-shadow из  typescript-eslint 4.0+, что позволяет обойти возникающий баг.

2021-02-26 10:25 UTC, Heymdall approved these changes

2021-03-01 08:58 UTC, voronin-ivan approved these changes
Было бы круто добавить тест на исходный кейс, в котором была ошибка

2021-03-01 08:58 UTC, voronin-ivan commented on package.json
> +        "@typescript-eslint/parser": "4.0.0",
я бы и сам typescript тогда уж обновил

2021-03-01 09:32 UTC, PoytaL commented on package.json
> +        "@typescript-eslint/parser": "4.0.0",
Добавил тест кейс и повысил версию

2021-03-01 10:22 UTC, voronin-ivan requested changes
У нас формируется ченжлог, сейчас по твоим сообщениям в коммитах непонятно, что зависимости обновились. Я бы сделал так: первый коммит это обновление депсов и форматирование кода, а второй коммит уже про shadow

2021-03-01 10:22 UTC, voronin-ivan commented on package.json
> +        "@typescript-eslint/parser": "4.0.0",
Теперь вижу ворнинг `WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.`, решается обновлением до 4.15.2

2021-03-01 14:58 UTC, voronin-ivan approved these changes
Напиши плз причину отключения no-use-before-define, по коду всё ок

2021-03-02 08:24 UTC, PoytaL commented
Стандартное правило eslint 'no-use-before-define' отрабатывает не корректно при проверках

https://github.com/alfa-laboratory/arui-presets-lint/actions/runs/610415084

При наличии правила из @typescript-eslint базовое правило из eslint следует отключить

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-use-before-define.md#disallow-the-use-of-variables-before-they-are-defined-no-use-before-define

2021-03-04 09:12 UTC, Heymdall approved these changes

2021-03-10 08:12 UTC, stepancar approved these changes

2021-03-10 08:13 UTC, merged