Update typescript 3.x.x -> 4.0.0
alfa-laboratory/arui-presets-lint pull request #91
Opened 2020-08-25 16:30 UTC by etroynov

Был обновлен typescript с версии 3 до версии 4, работоспособность протестирована.

Релиз typescript 4 не содержит серьезных изменений:
https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/

2020-08-26 08:25 UTC, Luchanso approved these changes

2020-08-27 12:44 UTC, Heymdall commented on yarn.lock
> +<<<<<<< HEAD
Кажется тут что-то пошло не так

2020-09-10 12:31 UTC, voronin-ivan requested changes

2020-09-10 12:31 UTC, voronin-ivan commented on yarn.lock
> +<<<<<<< HEAD
актуально, из-за этого ошибка установки зависимостей

2020-09-11 14:17 UTC, etroynov commented
сейчас в мастере 4.2.3 в релизе 5.1.2 откуда мне подмержить чтобы актуализировать?

2020-09-15 10:36 UTC, voronin-ivan commented
Из мастера, просто сейчас сломано обновление версии в самом package.json

2021-01-25 07:59 UTC, voronin-ivan commented
@etroynov, есть возможность добить пр?

2021-03-10 08:14 UTC, voronin-ivan commented
Влито в рамках https://github.com/alfa-laboratory/arui-presets-lint/pull/122, закрываю

2021-03-10 08:14 UTC, closed without merging